---
- hosts: {{ deployment }}
  connection: local
  name: Set BIOS attributes for HTTP boot
  gather_facts: False

  tasks:

  - name: Set BIOS config for HTTP boot (Enable HTTP boot)
    community.general.redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attributes:
        PxeDev1EnDis: "Disabled"
        PxeDev2EnDis: "Disabled"
        PxeDev3EnDis: "Disabled"
        PxeDev4EnDis: "Disabled"
        HttpDev1EnDis: "Enabled"
        HttpDev2EnDis: "Enabled"
        HttpDev3EnDis: "Enabled"
        HttpDev4EnDis: "Enabled"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: bios_attribute_http

  - name: Set BIOS config for HTTP boot (Disable DHCP, Enable VLAN)
    community.general.redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attributes:
        HttpDev1VlanEnDis: "Enabled"
        HttpDev1DnsDhcpEnDis: "Disabled"
        HttpDev1DhcpEnDis: "Disabled"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: bios_attribute_dhcp

  - name: Set BIOS config for HTTP boot (Set IP)
    community.general.redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attributes:
        HttpDev1Uri: "http://10.37.0.26/{{ fqdn }}/mboot.efi"
        HttpDev1Protocol: "IPv4"
        HttpDev1VlanId: "{{ vlan }}"
        HttpDev1Dns1: "{{ dns1 }}"
        HttpDev1Dns2: "{{ dns2 }}"
        HttpDev1Ip: "{{ ip }}"
        HttpDev1Mask: "{{ netmask }}"
        HttpDev1Gateway: "{{ gateway }}"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: bios_attribute_ip

  - name: Set BIOS config for cpu settings
    community.general.redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attributes:
        LogicalProc: "Enabled"
        CpuInterconnectBusSpeed: "MaxDataRate"
        ProcVirtualization: "Enabled"
        ProcAdjCacheLine: "Enabled"
        ProcHwPrefetcher: "Enabled"
        ProcSwPrefetcher: "Enabled"
        DcuIpPrefetcher: "Enabled"
        DcuStreamerPrefetcher: "Enabled"
        LlcPrefetch: "Disabled"
        UpiPrefetch: "Enabled"
        DeadLineLlcAlloc: "Enabled"
        DirectoryAtoS: "Disabled"
        ProcConfigTdp: "Nominal"
        ProcX2Apic: "Enabled"
        ControlledTurbo: "Disabled"
        ProcCores: "All"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: bios_attribute_cpu

  - name: Create BIOS configuration job (schedule BIOS setting update)
    community.general.idrac_redfish_command:
      category: Systems
      command: CreateBiosConfigJob
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    when: "bios_attribute_cpu.changed or bios_attribute_http.changed or bios_attribute_dhcp.changed or bios_attribute_ip.changed"

  - name: Set one-time boot device to UefiHttp
    redfish_command:
      category: Systems
      command: SetOneTimeBoot
      #bootdevice: "BiosSetup"
      bootdevice: "UefiHttp"
      #uefi_target: "{{ uefi_target }}"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"

#  - name: Reboot system
#    redfish_command:
#      category: Systems
#      command: PowerReboot
#      baseuri: "{{ baseuri }}"
#      username: "{{ username }}"
#      password: "{{ password }}"


